Repository CS2103-AY1819S2-W09-2/main, pull requests merged in 2019-04, with the labels that each got.

#137 Implement StatusBarFooter + Autocomplete Feature + Set Reminder Feature
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/history_command.png
  docs/images/huichun66.png
  docs/images/reminder_command.png
  docs/images/work_in_progress.png
  docs/team/brohandev.adoc
  docs/team/daviddl9.adoc
  docs/team/huichun.adoc
  docs/team/jing1324.adoc
  docs/team/lookuz.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Commands.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListCommandParser.java
  src/main/java/seedu/address/logic/commands/SetReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetReminderCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/ui/AutoCompleteTextField.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HealthWorkerCard.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RequestCard.java
  src/main/java/seedu/address/ui/RequestListPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HealthWorkerListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WhiteTheme.css
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/HealthWorkerCardHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/SetReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/healthworker/AddHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/request/AddRequestCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/InfoPanelTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#140 Changes to UserGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Medium

#150 Updating PPP, User Guide and Developer Guide
  .gitignore
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/lookuz.adoc
Labels: status.Ongoing

#161 Addition to Developer Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/lookuz.adoc
  src/main/java/seedu/address/model/person/Nric.java
Labels: priority.Medium, type.Task

#201 Fixed bug in FilterHealthWorkerCommand
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/tag/Specialisation.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/tag/SpecialisationTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/EditPersonCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: severity.Medium, type.Bug, type.Task

#214 Lucas: Changes to Developer Guide & Updated DeleteHealthWorkerCommand
  data/healthworkerbook.json
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/FilterCommandParserLogicSD.png
  docs/images/FilterHealthWorkerSD.png
  docs/images/filter_healthworker_UG.png
  docs/team/lookuz.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/request/DeleteRequestCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RequestBook.java
  src/main/java/seedu/address/model/person/healthworker/HealthWorker.java
  src/main/java/seedu/address/model/request/UniqueRequestList.java
  src/test/data/JsonSerializableHealthWorkerBookTest/typicalhealthworkersbook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/healthworker/DeleteHealthWorkerCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/healthworker/HealthWorkerTest.java
  src/test/java/seedu/address/model/request/UniqueRequestListTest.java
  src/test/java/seedu/address/testutil/TypicalHealthWorkers.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Medium, severity.Medium, type.Bug

#216 Fix assign request command bug
  data/healthworkerbook.json
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/request/AssignRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/DeleteRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/EditRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/RequestCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RequestBook.java
  src/main/java/seedu/address/model/request/Request.java
  src/main/java/seedu/address/model/request/UniqueRequestList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableRequestBookTest/typicalRequestsBook.json
  src/test/java/seedu/address/logic/commands/request/AssignRequestCommandTest.java
  src/test/java/seedu/address/logic/commands/request/CompleteRequestCommandTest.java
  src/test/java/seedu/address/logic/commands/request/EditRequestCommandTest.java
  src/test/java/seedu/address/logic/commands/request/FilterRequestCommandTest.java
  src/test/java/seedu/address/model/request/RequestTest.java
  src/test/java/seedu/address/storage/JsonSerializableRequestBookTest.java
  src/test/java/seedu/address/testutil/RequestBuilder.java
  src/test/java/seedu/address/testutil/TypicalRequests.java
Labels: priority.High

#215 Lucas: Improvements to FilterCommandParser and EditHealthWorkerCommand
  config/checkstyle/checkstyle.xml
  data/healthworkerbook.json
  docs/DeveloperGuide.adoc
  docs/images/FilterCommandParserLogicSD.png
  docs/images/FilterHealthWorkerSD.png
  docs/images/modelUmlDiagram.jpg
  docs/images/modelUmlDiagram.png
  docs/team/daviddl9.adoc
  src/main/java/seedu/address/logic/commands/DeleteHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/EditHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/HealthWorkerCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RequestBook.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/request/UniqueRequestList.java
  src/main/java/seedu/address/model/tag/Skills.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/healthworker/AddHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/healthworker/EditHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/request/AddRequestCommandTest.java
  src/test/java/seedu/address/logic/commands/request/AssignRequestCommandTest.java
  src/test/java/seedu/address/logic/commands/request/EditRequestCommandTest.java
  src/test/java/seedu/address/logic/commands/request/SelectRequestCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HealthHubParserTest.java
  src/test/java/seedu/address/model/HealthWorkerBookTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/request/UniqueRequestListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableRequestBookTest.java
  src/test/java/systemtests/DeleteRequestCommandSystemTest.java
  src/test/java/systemtests/HealthHubSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#222 Lucas: Updating PPP and Developer Guide
  docs/DeveloperGuide.adoc
  docs/team/lookuz.adoc
Labels: priority.Medium
