Repository CS2103-AY1819S2-W09-2/main, pull requests merged in 2019-03, with the labels that each got.

#33 [ Ready for Review] Lucas: Modifying Add Command to facilitate adding of HealthWorker objects
  src/main/java/seedu/address/logic/commands/AddHealthWorkerCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CommandMode.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniqueHealthWorkerList.java
  src/main/java/seedu/address/model/tag/Skills.java
  src/main/java/seedu/address/model/tag/Specialisation.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniqueHealthWorkerListTest.java
  src/test/java/seedu/address/testutil/TypicalHealthWorkers.java
Labels: priority.High, type.Story

#27 [ In-Progress ] Converting the UI to Health Hub's mock up design
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/health_hub_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MapPanel.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/MapPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/MapPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.Medium

#39 [Ready for Review]Lucas: Modified AddCommand classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/HealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/PersonCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CommandMode.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/healthworker/HealthWorker.java
  src/main/java/seedu/address/model/person/healthworker/Organization.java
  src/main/java/seedu/address/model/person/healthworker/UniqueHealthWorkerList.java
  src/main/java/seedu/address/model/request/Request.java
  src/main/java/seedu/address/storage/JsonAdaptedHealthWorker.java
  src/main/java/seedu/address/storage/JsonAdaptedRequest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/healthworker/HealthWorkerTest.java
  src/test/java/seedu/address/model/person/healthworker/OrganizationTest.java
  src/test/java/seedu/address/model/person/healthworker/UniqueHealthWorkerListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedHealthWorkerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRequestTest.java
  src/test/java/seedu/address/testutil/HealthWorkerBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/RequestBuilder.java
  src/test/java/seedu/address/testutil/TypicalHealthWorkers.java
  src/test/java/systemtests/AddPersonCommandSystemTest.java
Labels: type.Enhancement

#49 [In-Progress] Lucas: Creating HealthWorkerBook classes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/PersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CommandMode.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/HealthWorkerBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyHealthWorkerBook.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/model/VersionedBook.java
  src/main/java/seedu/address/model/VersionedHealthWorkerBook.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/EditPersonCommandSystemTest.java
Labels: type.Enhancement

#55 [IReady for Review] Lucas: Implemented functionality for EditHealthWorkerCommand
  src/main/java/seedu/address/logic/commands/EditHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CommandMode.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditHealthWorkerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/systemtests/EditPersonCommandSystemTest.java
Labels: priority.High, type.Enhancement, type.Story

#57 [Ready-for-review] Create versioned requestbook
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RequestBook.java
  src/main/java/seedu/address/model/VersionedRequestBook.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/model/VersionedRequestBookTest.java
  src/test/java/seedu/address/testutil/RequestBookBuilder.java
Labels: priority.High

#72 [In-Progress] Lucas: Creating DeleteHealthWorkerCommand
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CommandMode.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/systemtests/DeletePersonCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.High, status.Ongoing, type.Story

#101 Updated UI Skeleton
  data/addressbook.json
  src/main/java/seedu/address/ui/HealthWorkerCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HealthWorkerListCard.fxml
  src/main/resources/view/HealthWorkerListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/WhiteTheme.css
  src/main/resources/view/default.html
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/seedu/address/ui/testutil/UiPartRule.java
Labels: priority.Medium, severity.Medium, status.Ongoing

#105 [Ready-for-Review] Modifying Add/Edit/DeleteCommand for HealthWorker. Reworking Add/Edit/DeleteCommandParser.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/HealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/request/AddRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/DeleteRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/EditRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/RequestCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CommandMode.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.Medium, type.Enhancement

#112 [Ready-for-Review] Modified List Command class
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListCommandParser.java
  src/main/java/seedu/address/logic/commands/ListHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/request/ListRequestCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/request/ListRequestCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandModeTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.Medium, type.Enhancement

#114 Ready for review: Create select request command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/request/ListRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/SelectRequestCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteRequestParser.java
  src/main/java/seedu/address/logic/parser/SelectRequestCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/request/SelectRequestCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteRequestParserTest.java
  src/test/java/seedu/address/logic/parser/SelectRequestCommandParserTest.java
Labels: type.Story

#109 Refractor PersonCard, PersonListHandle to RequestCard, RequestListHandle + UI changes.
  data/healthworkerbook.json
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/tag/Condition.java
  src/main/java/seedu/address/storage/JsonAdaptedCondition.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRequest.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/RequestCard.java
  src/main/java/seedu/address/ui/RequestListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RequestListCard.fxml
  src/main/resources/view/RequestListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/WhiteTheme.css
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/RequestCardHandle.java
  src/test/java/guitests/guihandles/RequestListPanelHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRequestTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/RequestBuilder.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/RequestCardTest.java
  src/test/java/seedu/address/ui/RequestListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High

#116 Created Assign Request command
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/request/AssignRequestCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/healthworker/HealthWorker.java
  src/main/java/seedu/address/model/request/Request.java
  src/test/java/seedu/address/logic/commands/request/AssignRequestCommandTest.java
Labels: priority.High, type.Story

#117 Fix HealthWorker fullName() error
  src/main/java/seedu/address/logic/commands/request/AddRequestCommand.java
  src/main/java/seedu/address/logic/commands/request/RequestCommand.java
  src/main/java/seedu/address/model/request/Request.java
  src/test/java/seedu/address/logic/commands/request/AssignRequestCommandTest.java
Labels: type.Bug

#118 Fixed error where requestbook and healthworkerbook does not save
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Bug

#113 [Ready-for-Review] Modifying Select and Find Command
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/healthworker/HealthWorker.java
  src/main/java/seedu/address/model/person/healthworker/Organization.java
  src/main/java/seedu/address/model/tag/Skills.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableHealthWorkerBookTest/typicalhealthworkersbook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterHealthWorkerCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/healthworker/HealthWorkerTest.java
  src/test/java/seedu/address/model/person/healthworker/OrganizationTest.java
  src/test/java/seedu/address/model/tag/SkillsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRequestTest.java
  src/test/java/seedu/address/storage/JsonRequestBookStorageTest.java
  src/test/java/seedu/address/testutil/TypicalHealthWorkers.java
  src/test/java/seedu/address/ui/RequestListPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Medium, status.Ongoing, type.Enhancement, type.Story

#121 Refractor MapPanel to InfoPanel + UI changes
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/work_in_progress.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/request/RequestDate.java
  src/main/java/seedu/address/storage/JsonAdaptedRequest.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RequestCard.java
  src/main/java/seedu/address/ui/RequestListPanel.java
  src/main/resources/images/patient.png
  src/main/resources/view/HealthWorkerListCard.fxml
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RequestListCard.fxml
  src/main/resources/view/WhiteTheme.css
  src/test/java/guitests/guihandles/InfoPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/InfoPanelTest.java
  src/test/java/seedu/address/ui/MapPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: severity.Low, type.Enhancement

#120 Fixed bugs in Command and CommandParser classes.
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: severity.High, type.Bug

#124 Fixed non-responsive bug in FilterCommandParser on empty fields.
  data/healthworkerbook.json
  src/main/java/seedu/address/logic/commands/FilterHealthWorkerCommand.java
  src/main/java/seedu/address/logic/commands/request/FilterRequestCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/RequestPredicateUtil.java
  src/main/java/seedu/address/logic/parser/request/FindRequestParser.java
  src/test/java/seedu/address/logic/commands/request/FilterRequestCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: severity.Low, type.Bug

#133 Added SelectedRequestListener UI change + Further Implementation
  config/travis/check-trailing-whitespace.sh
  src/main/java/seedu/address/model/request/Request.java
  src/main/java/seedu/address/storage/JsonAdaptedRequest.java
  src/main/java/seedu/address/ui/HealthWorkerCard.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RequestListPanel.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/font-awesome/css/all.min.css
  src/main/resources/font-awesome/css/brands.min.css
  src/main/resources/font-awesome/css/fontawesome.min.css
  src/main/resources/font-awesome/css/regular.min.css
  src/main/resources/font-awesome/css/solid.min.css
  src/main/resources/font-awesome/css/svg-with-js.min.css
  src/main/resources/font-awesome/css/v4-shims.min.css
  src/main/resources/font-awesome/webfonts/fa-brands-400.eot
  src/main/resources/font-awesome/webfonts/fa-brands-400.svg
  src/main/resources/font-awesome/webfonts/fa-brands-400.ttf
  src/main/resources/font-awesome/webfonts/fa-brands-400.woff
  src/main/resources/font-awesome/webfonts/fa-brands-400.woff2
  src/main/resources/font-awesome/webfonts/fa-regular-400.eot
  src/main/resources/font-awesome/webfonts/fa-regular-400.svg
  src/main/resources/font-awesome/webfonts/fa-regular-400.ttf
  src/main/resources/font-awesome/webfonts/fa-regular-400.woff
  src/main/resources/font-awesome/webfonts/fa-regular-400.woff2
  src/main/resources/font-awesome/webfonts/fa-solid-900.eot
  src/main/resources/font-awesome/webfonts/fa-solid-900.svg
  src/main/resources/font-awesome/webfonts/fa-solid-900.ttf
  src/main/resources/font-awesome/webfonts/fa-solid-900.woff
  src/main/resources/font-awesome/webfonts/fa-solid-900.woff2
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/RequestListCard.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/WhiteTheme.css
  src/main/resources/view/default.html
  src/test/java/guitests/guihandles/HealthWorkerCardHandle.java
  src/test/java/guitests/guihandles/InfoPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/HealthWorkerCardTest.java
  src/test/java/seedu/address/ui/InfoPanelTest.java
  src/test/java/seedu/address/ui/RequestCardTest.java
  src/test/java/seedu/address/ui/RequestListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#135 Implement system tests and additional component tests.
  src/main/java/seedu/address/ui/RequestListPanel.java
  src/test/java/guitests/guihandles/HealthWorkerListPanelHandle.java
  src/test/java/guitests/guihandles/InfoPanelHandle.java
  src/test/java/guitests/guihandles/RequestCardHandle.java
  src/test/java/guitests/guihandles/RequestListPanelHandle.java
  src/test/java/seedu/address/ui/HealthWorkerListPanelTest.java
  src/test/java/seedu/address/ui/RequestListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High

#136 Adding tests for Logic Components
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/request/EditRequestCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteRequestParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/request/FindRequestParser.java
  src/main/java/seedu/address/logic/parser/request/RequestDatePredicateUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/request/Request.java
  src/main/java/seedu/address/model/request/RequestDate.java
  src/main/java/seedu/address/model/tag/Condition.java
  src/main/java/seedu/address/storage/JsonAdaptedCondition.java
  src/main/java/seedu/address/storage/JsonAdaptedRequest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/request/EditRequestCommandTest.java
  src/test/java/seedu/address/logic/commands/request/FilterRequestCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteRequestParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/request/RequestDatePredicateUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRequestTest.java
  src/test/java/seedu/address/testutil/EditRequestDescriptorBuilder.java
  src/test/java/systemtests/AddPersonCommandSystemTest.java
  src/test/java/systemtests/EditPersonCommandSystemTest.java
Labels: priority.Medium, severity.Medium, type.Task
